- name: "SCORED | 3.1.1 | Ensure IP forwarding is disabled"
  sysctl:
    name: '{{ item.name }}'
    value: '{{ item.value }}'
    sysctl_set: yes
    state: present
    reload: yes
    ignoreerrors: yes
  with_items:
    - { name: net.ipv4.ip_forward, value: 0 }
    - { name: net.ipv4.conf.all.ip_forward, value: 0 }
    - { name: net.ipv6.conf.all.forwarding, value: 0 }
  notify:
    - sysctl flush ipv4 route table
  when:
    - rhel8cis_is_router == false
    - rhel8cis_rule_3_1_1
  tags:
    - level1
    - sysctl
    - rule_3.1.1
    - rhel8_section3

- name: "SCORED | 3.1.2 | Ensure packet redirect sending is disabled"
  sysctl:
    name: '{{ item.name }}'
    value: '{{ item.value }}'
    sysctl_set: yes
    state: present
    reload: yes
    ignoreerrors: yes
  with_items:
    - { name: net.ipv4.conf.all.send_redirects, value: 0 }
    - { name: net.ipv4.conf.default.send_redirects, value: 0 }
  notify:
    - sysctl flush ipv4 route table
  when:
    - rhel8cis_is_router == false
    - rhel8cis_rule_3_1_2
  tags:
    - level1
    - sysctl
    - rule_3.1.2
    - rhel8_section3

- name: "SCORED | 3.2.1 | Ensure source routed packets are not accepted"
  sysctl:
    name: '{{ item.name }}'
    value: '{{ item.value }}'
    sysctl_set: yes
    state: present
    reload: yes
    ignoreerrors: yes
  with_items:
    - { name: net.ipv4.conf.all.accept_source_route, value: 0 }
    - { name: net.ipv4.conf.default.accept_source_route, value: 0 }
    - { name: net.ipv6.conf.all.accept_source_route, value: 0 }
    - { name: net.ipv6.conf.default.accept_source_route, value: 0 }
  notify:
    - sysctl flush ipv4 route table
  when:
    - rhel8cis_rule_3_2_1
  tags:
    - level1
    - sysctl
    - rule_3.2.1
    - rhel8_section3

- name: "SCORED | 3.2.2 | Ensure ICMP redirects are not accepted"
  sysctl:
    name: '{{ item.name }}'
    value: '{{ item.value }}'
    sysctl_set: yes
    state: present
    reload: yes
    ignoreerrors: yes
  with_items:
    - { name: net.ipv4.conf.all.accept_redirects, value: 0 }
    - { name: net.ipv4.conf.default.accept_redirects, value: 0 }
    - { name: net.ipv6.conf.all.accept_redirects, value: 0 }
    - { name: net.ipv6.conf.default.accept_redirects, value: 0 }
  notify:
    - sysctl flush ipv4 route table
  when:
    - rhel8cis_rule_3_2_2
  tags:
    - level1
    - sysctl
    - rule_3.2.2
    - rhel8_section3

- name: "SCORED | 3.2.3 | Ensure secure ICMP redirects are not accepted"
  sysctl:
    name: '{{ item.name }}'
    value: '{{ item.value }}'
    sysctl_set: yes
    state: present
    reload: yes
    ignoreerrors: yes
  with_items:
    - { name: net.ipv4.conf.all.secure_redirects, value: 0 }
    - { name: net.ipv4.conf.default.secure_redirects, value: 0 }
  notify:
    - sysctl flush ipv4 route table
  when:
    - rhel8cis_rule_3_2_3
  tags:
    - level1
    - sysctl
    - rule_3.2.3
    - rhel8_section3

- name: "SCORED | 3.2.4 | Ensure suspicious packets are logged"
  sysctl:
    name: '{{ item.name }}'
    value: '{{ item.value }}'
    sysctl_set: yes
    state: present
    reload: yes
    ignoreerrors: yes
  with_items:
    - { name: net.ipv4.conf.all.log_martians, value: 1 }
    - { name: net.ipv4.conf.default.log_martians, value: 1 }
  notify:
    - sysctl flush ipv4 route table
  when:
    - rhel8cis_rule_3_2_4
  tags:
    - level1
    - sysctl
    - rule_3.2.4
    - rhel8_section3

- name: "SCORED | 3.2.5 | Ensure broadcast ICMP requests are ignored"
  sysctl:
    name: net.ipv4.icmp_echo_ignore_broadcasts
    value: 1
    state: present
    reload: yes
    ignoreerrors: yes
  notify:
    - sysctl flush ipv4 route table
  when:
    - rhel8cis_rule_3_2_5
  tags:
    - level1
    - sysctl
    - rule_3.2.5
    - rhel8_section3

- name: "SCORED | 3.2.6 | Ensure bogus ICMP responses are ignored"
  sysctl:
    name: net.ipv4.icmp_ignore_bogus_error_responses
    value: 1
    state: present
    reload: yes
    ignoreerrors: yes
  notify:
    - sysctl flush ipv4 route table
  when:
    - rhel8cis_rule_3_2_6
  tags:
    - level1
    - sysctl
    - rule_3.2.6
    - rhel8_section3

- name: "SCORED | 3.2.7 | Ensure Reverse Path Filtering is enabled"
  sysctl:
    name: '{{ item.name }}'
    value: '{{ item.value }}'
    sysctl_set: yes
    state: present
    reload: yes
    ignoreerrors: yes
  with_items:
    - { name: net.ipv4.conf.all.rp_filter, value: 1 }
    - { name: net.ipv4.conf.default.rp_filter, value: 1 }
  notify:
    - sysctl flush ipv4 route table
  when:
    - rhel8cis_rule_3_2_7
  tags:
    - level1
    - sysctl
    - rule_3.2.7
    - rhel8_section3

- name: "SCORED | 3.2.8 | Ensure TCP SYN Cookies is enabled"
  sysctl:
    name: net.ipv4.tcp_syncookies
    value: 1
    state: present
    reload: yes
    ignoreerrors: yes
  notify:
    - sysctl flush ipv4 route table
  when:
    - rhel8cis_rule_3_2_8
  tags:
    - level1
    - sysctl
    - rule_3.2.8
    - rhel8_section3

- name: "SCORED | 3.2.9 | Ensure IPv6 router advertisements are not accepted"
  sysctl:
    name: '{{ item.name }}'
    value: '{{ item.value }}'
    sysctl_set: yes
    state: present
    reload: yes
    ignoreerrors: yes
  with_items:
    - { name: net.ipv6.conf.all.accept_ra, value: 0 }
    - { name: net.ipv6.conf.default.accept_ra, value: 0 }
  notify:
    - sysctl flush ipv6 route table
  when:
    - rhel8cis_rule_3_2_9
  tags:
    - level1
    - sysctl
    - rule_3.2.9
    - rhel8_section3

- name: "NOTSCORED | 3.3.1 | Ensure DCCP is disabled"
  lineinfile:
    dest: /etc/modprobe.d/CIS.conf
    regexp: "^(#)?install dccp(\\s|$)"
    line: "install dccp /bin/true"
    create: yes
  when:
    - rhel8cis_rule_3_3_1
  tags:
    - level1
    - rule_3.3.1
    - rhel8_section3

- name: "NOTSCORED | 3.3.2 | Ensure SCTP is disabled"
  lineinfile:
    dest: /etc/modprobe.d/CIS.conf
    regexp: "^(#)?install sctp(\\s|$)"
    line: "install sctp /bin/true"
    create: yes
  when:
    - rhel8cis_rule_3_3_2
  tags:
    - level1
    - rule_3.3.2
    - rhel8_section3

- name: "NOTSCORED | 3.3.3 | Ensure RDS is disabled"
  lineinfile:
    dest: /etc/modprobe.d/CIS.conf
    regexp: "^(#)?install rds(\\s|$)"
    line: "install rds /bin/true"
    create: yes
  when:
    - rhel8cis_rule_3_3_3
  tags:
    - level1
    - rule_3.3.3
    - rhel8_section3

- name: "NOTSCORED | 3.3.4 | Ensure TIPC is disabled"
  lineinfile:
    dest: /etc/modprobe.d/CIS.conf
    regexp: "^(#)?install tipc(\\s|$)"
    line: "install tipc /bin/true"
    create: yes
  when:
    - rhel8cis_rule_3_3_4
  tags:
    - level1
    - rule_3.3.4
    - rhel8_section3

- name: "SCORED | 3.4.2 | Ensure firewalld package is installed"
  systemd:
    name: firewalld
    state: started
    enabled: yes
  when: rhel8cis_firewall == "firewalld"
  tags:
    - level1
    - rule_3.4.2
    - rhel8_section3

- name: "SCORED | 3.4.2.1 | Ensure firewalld service is enabled and running | CUSTOM"
  systemd:
    name: firewalld
    state: started
    enabled: yes
  when: rhel8cis_firewall == "firewalld"
  tags:
    - level1
    - rule_3.4.2.1
    - rhel8_section3

- name: "SCORED | 3.4.2.2 | Ensure iptables is not enabled"
  systemd:
    name: iptables
    enabled: no
    masked: yes
  when:
    - rhel8cis_firewall == "firewalld"
    - packages['iptables-services'] is defined
  tags:
    - level1
    - rule_3.4.2.2
    - rhel8_section3

- name: "SCORED | 3.4.2.3 | Ensure nftables is not enabled"
  systemd:
    name: nftables
    enabled: no
    masked: yes
  when:
    - rhel8cis_firewall == "firewalld"
    - rhel8cis_rule_3_4_2_3
  tags:
    - level1
    - rule_3.4.2.3
    - rhel8_section3

- name: "SCORED | 3.4.2.4 | Ensure default zone is set"
  block:
    - name: "Get default Firewalld zone"
      command: firewall-cmd --get-default-zone
      register: firewalld_zone

    - name: "Set default Firewalld zone"
      command: firewall-cmd --set-default-zone=public
      when:
        - firewalld_zone.stdout != "public"
  when:
    - rhel8cis_firewall == "firewalld"
    - rhel8cis_rule_3_4_2_4
  tags:
    - level1
    - rule_3.4.2.4
    - rhel8_section3

- name: "SCORED | 3.4.2.5 | Ensure network interfaces are assigned to appropriate zone"
  command: /bin/true
  when:
    - rhel8cis_firewall == "firewalld"
    - rhel8cis_rule_3_4_2_5
  tags:
    - level1
    - rule_3.4.2.5
    - rhel8_section3

- name: "SCORED | 3.4.2.6 | Ensure unnecessary services and ports are not accepted"
  command: /bin/true
  when:
    - rhel8cis_firewall == "firewalld"
    - rhel8cis_rule_3_4_2_6
  tags:
    - level1
    - rule_3.4.2.6
    - rhel8_section3

- name: "SCORED | 3.4.3 | Configure nftables"
  block:
    - name: "Nftables Rules"
      copy:
        source: etc/nftables/nftables.rules
        dest: /etc/nftables/nftables.rules
        owner: root
        group: root
        mode: 0644

    - name: "Load Nftables Rules"
      command: nft -f /etc/nftables/nftables.rules

    - name: "Make Nftables Rules Permanent"
      command: nft list ruleset >  /etc/nftables/nftables.rules

    - name: "Configure nftables.conf"
      lineinfile:
        dest: /etc/sysconfig/nftables.conf
        regexp: ^(#)?include\s+"\/etc/nftables/nftables.rules\"
        line: include "/etc/nftables/nftables.rules"
  when:
    - rhel8cis_firewall == "nftables"
    - rhel8cis_rule_3_4_3
  tags:
    - level1
    - rule_3.4.3
    - rhel8_section3
    - notimplemented

- name: "SCORED | 3.4.3.1 | Ensure network interfaces are assigned to appropriate zone"
  command: /bin/true
  changed_when: no
  when:
    - rhel8cis_firewall == "nftables"
    - rhel8cis_rule_3_4_3_1
  tags:
    - level1
    - rule_3.4.3.1
    - rhel8_section3

- name: "SCORED | 3.4.3.2 | Ensure a table exists"
  command: /bin/true
  changed_when: no
  when:
    - rhel8cis_firewall == "nftables"
    - rhel8cis_rule_3_4_3_2
  tags:
    - level1
    - rule_3.4.3.2
    - rhel8_section3

- name: "SCORED | 3.4.3.3 | Ensure base chains exist"
  command: /bin/true
  changed_when: no
  when:
    - rhel8cis_firewall == "nftables"
    - rhel8cis_rule_3_4_3_3
  tags:
    - level1
    - rule_3.4.3.3
    - rhel8_section3

- name: "SCORED | 3.4.3.4 | Ensure loopback traffic is configured"
  command: /bin/true
  changed_when: no
  when:
    - rhel8cis_firewall == "nftables"
    - rhel8cis_rule_3_4_3_4
  tags:
    - level1
    - rule_3.4.3.4
    - rhel8_section3

- name: "SCORED | 3.4.3.5 | Ensure outbound and established connections are configured"
  command: /bin/true
  changed_when: no
  when:
    - rhel8cis_firewall == "nftables"
    - rhel8cis_rule_3_4_3_5
  tags:
    - level1
    - rule_3.4.3.5
    - rhel8_section3

- name: "SCORED | 3.4.3.6 | Ensure default deny firewall policy"
  command: /bin/true
  changed_when: no
  when:
    - rhel8cis_firewall == "nftables"
    - rhel8cis_rule_3_4_3_6
  tags:
    - level1
    - rule_3.4.3.6
    - rhel8_section3

- name: "SCORED | 3.4.3.7 | Ensure nftables service is enabled"
  command: /bin/true
  changed_when: no
  when:
    - rhel8cis_firewall == "nftables"
    - rhel8cis_rule_3_4_3_7
  tags:
    - level1
    - rule_3.4.3.7
    - rhel8_section3

- name: "SCORED | 3.4.3.8 | Ensure nftables rules are permanent"
  command: /bin/true
  changed_when: no
  when:
    - rhel8cis_firewall == "nftables"
    - rhel8cis_rule_3_4_3_8
  tags:
    - level1
    - rule_3.4.3.8
    - rhel8_section3

- name: "SCORED | 3.4.4 | Configure iptables"
  command: /bin/true
  changed_when: no
  when:
    - rhel8cis_firewall == "iptables"
    - rhel8cis_rule_3_4_4
  tags:
    - level1
    - rule_3.4.4
    - rhel8_section3
    - notimplemented

- name: "SCORED | 3.4.4.1 | Configure IPv4 iptables"
  command: /bin/true
  changed_when: no
  when:
    - rhel8cis_firewall == "iptables"
    - rhel8cis_rule_3_4_4_1
  tags:
    - level1
    - rule_3.4.4.1
    - rhel8_section3
    - notimplemented

- name: "SCORED | 3.4.4.1.1 | Ensure default deny firewall policy"
  command: /bin/true
  changed_when: no
  when:
    - rhel8cis_firewall == "iptables"
    - rhel8cis_rule_3_4_4_1_1
  tags:
    - level1
    - rule_3.4.4.1.1
    - rhel8_section3
    - notimplemented

- name: "SCORED | 3.4.4.1.2 | Ensure loopback traffic is configured"
  command: /bin/true
  changed_when: no
  when:
    - rhel8cis_firewall == "iptables"
    - rhel8cis_rule_3_4_4_1_2
  tags:
    - level1
    - rule_3.4.4.1.2
    - rhel8_section3
    - notimplemented

- name: "SCORED | 3.4.4.1.3 | Ensure outbound and established connections are configured"
  command: /bin/true
  changed_when: no
  when:
    - rhel8cis_firewall == "iptables"
    - rhel8cis_rule_3_4_4_1_3
  tags:
    - level1
    - rule_3.4.4.1.3
    - rhel8_section3
    - notimplemented

- name: "SCORED | 3.4.4.1.4 | Ensure firewall rules exist for all open ports"
  command: /bin/true
  changed_when: no
  when:
    - rhel8cis_firewall == "iptables"
    - rhel8cis_rule_3_4_4_1_4
  tags:
    - level1
    - rule_3.4.4.1.4
    - rhel8_section3
    - notimplemented

- name: "SCORED | 3.4.4.2 | Configure IPv6 iptables"
  command: /bin/true
  changed_when: no
  when:
    - rhel8cis_firewall == "iptables"
    - rhel8cis_rule_3_4_4_2
  tags:
    - level1
    - rule_3.4.4.2
    - rhel8_section3
    - notimplemented

- name: "SCORED | 3.4.4.2.1 | Ensure IPv6 default deny firewall policy"
  command: /bin/true
  changed_when: no
  when:
    - rhel8cis_firewall == "iptables"
    - rhel8cis_rule_3_4_4_2_1
  tags:
    - level1
    - rule_3.4.4.2.1
    - rhel8_section3
    - notimplemented

- name: "SCORED | 3.4.4.2.2 | Ensure IPv6 loopback traffic is configured"
  command: /bin/true
  changed_when: no
  when:
    - rhel8cis_firewall == "iptables"
    - rhel8cis_rule_3_4_4_2_2
  tags:
    - level1
    - rule_3.4.4.2.2
    - rhel8_section3
    - notimplemented

- name: "SCORED | 3.4.4.2.3 | Ensure IPv6 outbound and established connections are configured"
  command: /bin/true
  changed_when: no
  when:
    - rhel8cis_firewall == "iptables"
    - rhel8cis_rule_3_4_4_2_3
  tags:
    - level1
    - rule_3.4.4.2.3
    - rhel8_section3
    - notimplemented

- name: "SCORED | 3.4.4.2.4 | Ensure IPv6 firewall rules exist for all open ports"
  command: /bin/true
  changed_when: no
  when:
    - rhel8cis_firewall == "iptables"
    - rhel8cis_rule_3_4_4_2_4
  tags:
    - level1
    - rule_3.4.4.2.4
    - rhel8_section3
    - notimplemented

- name: "SCORED | 3.5 | Ensure wireless interfaces are disabled"
  command: /bin/true
  changed_when: no
  when:
    - rhel8cis_rule_3_5
  tags:
    - level1
    - rule_3.5
    - rhel8_section3
    - notimplemented

- name: "NOTSCORED | 3.6 | Ensure IPv6 is disabled"
  block:
    - name: "SCORED | 3.6 | Ensure permissions on bootloader config are configured" # Modified SI Baseline
      stat:
        path: /etc/grub2-efi.cfg
      register: grub_cfg

    - name: "SCORED | 3.6 | Ensure permissions on bootloader config are configured"
      file:
        path: "{{ grub_cfg.stat.lnk_source }}"
        owner: root
        group: root
        mode: 0600
      when:
        - grub_cfg.stat.exists and grub_cfg.stat.islnk

    - name: "SCORED | 3.6 | Ensure permissions on bootloader config are configured"
      replace:
        dest: /etc/default/grub
        regexp: '(^GRUB_CMDLINE_LINUX\s*\=\s*)(?:")(.+)(?<!ipv6.disable=1)(?:")'
        replace: '\1"\2 ipv6.disable=1"'
        follow: yes
      ignore_errors: yes
      notify: generate new grub config
  when:
    - rhel8cis_ipv6_required == false
    - rhel8cis_rule_3_6
  tags:
    - level1
    - rule_3.6
    - rhel8_section3
